[package]
name = "xyra_derive"
version = "1.0.0"
authors = ["jprugel <jonathon.prugel@gmail.com>"]
description = "A sister crate for xyra including a component derive macro"
edition = "2021"

[lib]
proc-macro = true

[dependencies]


